/******************************************************************************
 * Top contributors (to current version):
 *   Zvika Berger
 *
 * This file is part of the cvc5 project.
 *
 * Copyright (c) 2009-2025 by the authors listed in the file AUTHORS
 * in the top-level source directory and their institutional affiliations.
 * All rights reserved.  See the file COPYING in the top-level source
 * directory for licensing information.
 * ****************************************************************************
 *
 * Theory PBV rewriter.
 *
 * Applies the RW_B rewrite rule set (Appendix A) from:
 *   "Bit-Precise Reasoning with Parametric Bit-Vectors"
 *   Berger, Zohar, Niemetz, Preiner, Reynolds, Barrett, Tinelli (SAT 2025)
 *
 * The implementation of postRewrite is auto-generated by:
 *   python3 src/theory/pbv/generate_rewriter.py
 * into theory_pbv_rewriter.cpp.  Do not edit that file by hand.
 */

#include "cvc5_private.h"

#ifndef CVC5__THEORY__PBV__THEORY_PBV_REWRITER_H
#define CVC5__THEORY__PBV__THEORY_PBV_REWRITER_H

#include "theory/theory_rewriter.h"

namespace cvc5::internal {
namespace theory {
namespace pbv {

class TheoryPbvRewriter : public TheoryRewriter {
 public:
  TheoryPbvRewriter(NodeManager* nm) : TheoryRewriter(nm) {}

  /**
   * Post-rewrite: apply the full RW_B rule set (Appendix A).
   * Returns REWRITE_AGAIN_FULL when a rule fires; REWRITE_DONE otherwise.
   * Implementation is auto-generated into theory_pbv_rewriter.cpp.
   */
  RewriteResponse postRewrite(TNode node) override;

  /**
   * Pre-rewrite: no rules applied at this stage.
   */
  RewriteResponse preRewrite(TNode node) override {
    return RewriteResponse(REWRITE_DONE, node);
  }
};

}  // namespace pbv
}  // namespace theory
}  // namespace cvc5::internal

#endif  // CVC5__THEORY__PBV__THEORY_PBV_REWRITER_H
