/******************************************************************************
 * Top contributors (to current version):
 *   Zvika Berger
 *
 * This file is part of the cvc5 project.
 *
 * Copyright (c) 2009-2025 by the authors listed in the file AUTHORS
 * in the top-level source directory and their institutional affiliations.
 * All rights reserved.  See the file COPYING in the top-level source
 * directory for licensing information.
 * ****************************************************************************
 *
 * Theory PBV rewriter.
 *
 * Applies the RW_B rewrite rule set (Appendix A) from:
 *   "Bit-Precise Reasoning with Parametric Bit-Vectors"
 *   Berger, Zohar, Niemetz, Preiner, Reynolds, Barrett, Tinelli (SAT 2025)
 *
 * The implementation of postRewrite is auto-generated by:
 *   python3 src/theory/pbv/generate_rewriter.py
 * into theory_pbv_rewriter.cpp.  Do not edit that file by hand.
 */

#include "cvc5_private.h"

#ifndef CVC5__THEORY__PBV__THEORY_PBV_REWRITER_H
#define CVC5__THEORY__PBV__THEORY_PBV_REWRITER_H

#include "options/smt_options.h"
#include "theory/theory_rewriter.h"

namespace cvc5::internal {
namespace theory {
namespace pbv {

class TheoryPbvRewriter : public TheoryRewriter {
 public:
  /**
   * @param rwMw value of --pbv-rw-mw=MODE, selecting which opt-in rule
   * families to apply:
   *   none   neither (default)
   *   base   the `pbv-merge-*` rules: shift-of-shift merge, nested
   *          extension merge
   *   cav26  the `pbv-c26-*` rules: bitwise identities adapted from the
   *          parabit rule set
   *   all    both
   */
  TheoryPbvRewriter(NodeManager* nm,
                    options::PbvRwMwMode rwMw = options::PbvRwMwMode::NONE,
                    bool rwAc = false,
                    bool rwNnf = false,
                    bool rwBool = false,
                    uint64_t boolCap = 12,
                    bool rwShiftZext = false)
      : TheoryRewriter(nm),
        d_rwMerge(rwMw == options::PbvRwMwMode::BASE
                  || rwMw == options::PbvRwMwMode::ALL),
        d_rwCav26(rwMw == options::PbvRwMwMode::CAV26
                  || rwMw == options::PbvRwMwMode::ALL),
        d_rwAc(rwAc),
        d_rwNnf(rwNnf),
        d_rwBool(rwBool),
        d_boolCap(boolCap),
        d_rwShiftZext(rwShiftZext)
  {
  }

  /**
   * Post-rewrite: apply the full RW_B rule set (Appendix A).
   * Returns REWRITE_AGAIN_FULL when a rule fires; REWRITE_DONE otherwise.
   * Implementation is auto-generated into theory_pbv_rewriter.cpp.
   */
  RewriteResponse postRewrite(TNode node) override;

  /**
   * Pre-rewrite: no rules applied at this stage.
   */
  RewriteResponse preRewrite(TNode node) override {
    return RewriteResponse(REWRITE_DONE, node);
  }

 private:
  /** --pbv-rw-mw=base|all: enable the `pbv-merge-*` rules. */
  bool d_rwMerge;
  /** --pbv-rw-mw=cav26|all: enable the `pbv-c26-*` rules. */
  bool d_rwCav26;
  /** --pbv-rw-ac: AC-normalize pbvand/pbvor/pbvxor. */
  bool d_rwAc;
  /** --pbv-rw-nnf: push pbvnot inward through pbvand/pbvor (De Morgan). */
  bool d_rwNnf;
  /** --pbv-rw-bool: decide bitwise equalities by Boolean evaluation. */
  bool d_rwBool;
  /** --pbv-rw-bool-cap: give up past this many distinct leaves. */
  uint64_t d_boolCap;
  /** --pbv-rw-shift-zext-merge: merge shifts across a zero extension. */
  bool d_rwShiftZext;

  /** Gather the distinct non-bitwise leaves of a bitwise term. */
  static bool boolLeaves(TNode n, std::vector<Node>& leaves, uint64_t cap);
  /** Evaluate a bitwise term under an assignment (bit i of `asg` per leaf). */
  static bool boolEval(TNode n, const std::vector<Node>& leaves, uint64_t asg);
};

}  // namespace pbv
}  // namespace theory
}  // namespace cvc5::internal

#endif  // CVC5__THEORY__PBV__THEORY_PBV_REWRITER_H
