/******************************************************************************
 * AUTO-GENERATED by src/theory/pbv/generate_rewriter.py
 *
 * DO NOT EDIT BY HAND.  Re-generate by running:
 *   python3 src/theory/pbv/generate_rewriter.py
 *
 * Implements RW_B (Appendix A) from:
 *   "Bit-Precise Reasoning with Parametric Bit-Vectors"
 *   Berger, Zohar, Niemetz, Preiner, Reynolds, Barrett, Tinelli (SAT 2025)
 *
 * Source rules: src/theory/pbv/rewrites  (RARE DSL)
 * Parser:       src/rewriter/rw_parser.py
 *
 * Design principles (Section 4.1):
 *   (i)  No rule introduces a new bitwise PBV operator.
 *   (ii) The integer translation must not increase mod/pow2 occurrences.
 ******************************************************************************/

#include "theory/pbv/theory_pbv_rewriter.h"

#include <algorithm>
#include <vector>

#include "expr/node.h"
#include "expr/node_manager.h"
#include "theory/rewriter.h"
#include "util/rational.h"

namespace cvc5::internal {
namespace theory {
namespace pbv {

namespace {
/** Is this the all-zero constant `(int_to_pbv k 0)`? */
bool isZeroConst(TNode n)
{
  return n.getKind() == Kind::INT_TO_PBV && n.getNumChildren() == 2
         && n[1].isConst() && n[1].getConst<Rational>().sgn() == 0;
}
/** Does this node's top symbol act bitwise, so we can descend through it? */
bool isBitwise(TNode n)
{
  Kind k = n.getKind();
  return ((k == Kind::PBV_AND || k == Kind::PBV_OR || k == Kind::PBV_XOR)
          && n.getNumChildren() == 2)
         || (k == Kind::PBV_NOT && n.getNumChildren() == 1);
}
}  // namespace

bool TheoryPbvRewriter::boolLeaves(TNode n,
                                   std::vector<Node>& leaves,
                                   uint64_t cap)
{
  if (isZeroConst(n))
  {
    return true;  // the constant 0 contributes no variable
  }
  if (isBitwise(n))
  {
    for (size_t i = 0, m = n.getNumChildren(); i < m; ++i)
    {
      if (!boolLeaves(n[i], leaves, cap)) return false;
    }
    return true;
  }
  if (std::find(leaves.begin(), leaves.end(), Node(n)) == leaves.end())
  {
    if (leaves.size() >= cap) return false;
    leaves.emplace_back(n);
  }
  return true;
}

bool TheoryPbvRewriter::boolEval(TNode n,
                                 const std::vector<Node>& leaves,
                                 uint64_t asg)
{
  if (isZeroConst(n)) return false;
  Kind k = n.getKind();
  if (isBitwise(n))
  {
    if (k == Kind::PBV_NOT) return !boolEval(n[0], leaves, asg);
    bool a = boolEval(n[0], leaves, asg);
    bool b = boolEval(n[1], leaves, asg);
    if (k == Kind::PBV_AND) return a && b;
    if (k == Kind::PBV_OR) return a || b;
    return a != b;  // PBV_XOR
  }
  auto it = std::find(leaves.begin(), leaves.end(), Node(n));
  size_t idx = static_cast<size_t>(it - leaves.begin());
  return ((asg >> idx) & 1u) != 0;
}

RewriteResponse TheoryPbvRewriter::postRewrite(TNode node)
{
  NodeManager* nm = d_nm;
  // --- Kind::EQUAL ---
  if (node.getKind() == Kind::EQUAL)
  {
    // Rule: pbv-not-neq
    if (
(node[1].getKind() == Kind::PBV_NOT)        && (node[0] == node[1][0]))
    {
      Node rhs_pbv_not_neq = nm->mkConst(false);
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_not_neq);
    }

  }  // Kind::EQUAL

  // --- Kind::PBV_ADD ---
  if (node.getKind() == Kind::PBV_ADD)
  {
    // Rule: pbv-add-zero
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_add_zero = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_add_zero);
    }

    // Rule: pbv-c26-not-plus-one
    if (
d_rwCav26        && (node[0].getKind() == Kind::PBV_NOT)        && (node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(1)))
    {
      Node rhs_pbv_c26_not_plus_one = nm->mkNode(Kind::PBV_NEG, { node[0][0] });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_c26_not_plus_one);
    }

  }  // Kind::PBV_ADD

  // --- Kind::PBV_AND ---
  if (node.getKind() == Kind::PBV_AND)
  {
    // Rule: pbv-and-zero
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_and_zero = nm->mkNode(Kind::INT_TO_PBV, { node[1][0], nm->mkConstInt(Rational(0)) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_and_zero);
    }

    // Rule: pbv-reverse-extract-and
    if (
(node[0].getKind() == Kind::PBV_EXTRACT)        && (node[1].getKind() == Kind::PBV_EXTRACT)        && (node[0][1] == node[1][1])        && (node[0][2] == node[1][2]))
    {
      Node rhs_pbv_reverse_extract_and = nm->mkNode(Kind::PBV_EXTRACT, { nm->mkNode(Kind::PBV_AND, { node[0][0], node[1][0] }), node[0][1], node[0][2] });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_reverse_extract_and);
    }

    // Rule: pbv-c26-and-allones
    if (
d_rwCav26        && (node[1].getKind() == Kind::PBV_NOT)        && (node[1][0].getKind() == Kind::INT_TO_PBV)        && (node[1][0][1].isConst() && node[1][0][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_c26_and_allones = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_c26_and_allones);
    }

    // Rule: pbv-c26-and-self
    if (
d_rwCav26        && (node[0] == node[1]))
    {
      Node rhs_pbv_c26_and_self = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_c26_and_self);
    }

    // Rule: pbv-c26-and-not-self
    if (
d_rwCav26        && (node[1].getKind() == Kind::PBV_NOT)        && (node[0] == node[1][0]))
    {
      Node rhs_pbv_c26_and_not_self = nm->mkNode(Kind::INT_TO_PBV, { nm->mkNode(Kind::PBV_SIZE, { node[0] }), nm->mkConstInt(Rational(0)) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_c26_and_not_self);
    }

    // Rule: pbv-c26-and-one
    if (
d_rwCav26        && (node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(1)))
    {
      Node rhs_pbv_c26_and_one = nm->mkNode(Kind::PBV_ZERO_EXTEND, { nm->mkNode(Kind::SUB, { node[1][0], nm->mkConstInt(Rational(1)) }), nm->mkNode(Kind::PBV_EXTRACT, { node[0], nm->mkConstInt(Rational(0)), nm->mkConstInt(Rational(0)) }) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_c26_and_one);
    }

  }  // Kind::PBV_AND

  // --- Kind::PBV_ASHR ---
  if (node.getKind() == Kind::PBV_ASHR)
  {
    // Rule: pbv-ashr-by-const-0
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_ashr_by_const_0 = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_ashr_by_const_0);
    }

    // Rule: pbv-ashr-zero
    if (
(node[0].getKind() == Kind::INT_TO_PBV)        && (node[0][1].isConst() && node[0][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_ashr_zero = nm->mkNode(Kind::INT_TO_PBV, { node[0][0], nm->mkConstInt(Rational(0)) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_ashr_zero);
    }

  }  // Kind::PBV_ASHR

  // --- Kind::PBV_CONCAT ---
  if (node.getKind() == Kind::PBV_CONCAT)
  {
    // Rule: pbv-concat-extract-merge
    if (
(node[0].getKind() == Kind::PBV_EXTRACT)        && (node[1].getKind() == Kind::PBV_EXTRACT)        && (node[0][0] == node[1][0])        && node[0][2] == nm->mkNode(Kind::ADD, { node[1][1], nm->mkConstInt(Rational(1)) }))
    {
      Node rhs_pbv_concat_extract_merge = nm->mkNode(Kind::PBV_EXTRACT, { node[0][0], node[0][1], node[1][2] });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_concat_extract_merge);
    }

  }  // Kind::PBV_CONCAT

  // --- Kind::PBV_EXTRACT ---
  if (node.getKind() == Kind::PBV_EXTRACT)
  {
    // Rule: pbv-extract-extract
    if (
(node[0].getKind() == Kind::PBV_EXTRACT))
    {
      Node rhs_pbv_extract_extract = nm->mkNode(Kind::PBV_EXTRACT, { node[0][0], nm->mkNode(Kind::ADD, { node[0][2], node[1] }), nm->mkNode(Kind::ADD, { node[0][2], node[2] }) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_extract_extract);
    }

    // Rule: pbv-extract-whole
    if (
(node[2].isConst() && node[2].getConst<Rational>() == Rational(0))        && node[1] == nm->mkNode(Kind::SUB, { nm->mkNode(Kind::PBV_SIZE, { node[0] }), nm->mkConstInt(Rational(1)) }))
    {
      Node rhs_pbv_extract_whole = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_extract_whole);
    }

  }  // Kind::PBV_EXTRACT

  // --- Kind::PBV_LSHR ---
  if (node.getKind() == Kind::PBV_LSHR)
  {
    // Rule: pbv-lshr-by-const-0
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_lshr_by_const_0 = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_lshr_by_const_0);
    }

    // Rule: pbv-lshr-by-const-2
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][0] == node[1][1]))
    {
      Node rhs_pbv_lshr_by_const_2 = nm->mkNode(Kind::INT_TO_PBV, { node[1][0], nm->mkConstInt(Rational(0)) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_lshr_by_const_2);
    }

    // Rule: pbv-lshr-zero
    if (
(node[0].getKind() == Kind::INT_TO_PBV)        && (node[0][1].isConst() && node[0][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_lshr_zero = nm->mkNode(Kind::INT_TO_PBV, { node[0][0], nm->mkConstInt(Rational(0)) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_lshr_zero);
    }

    // Rule: pbv-merge-lshr
    if (
d_rwMerge        && (node[0].getKind() == Kind::PBV_LSHR))
    {
      Node rhs_pbv_merge_lshr = nm->mkNode(Kind::ITE, { nm->mkNode(Kind::PBV_UGE, { nm->mkNode(Kind::PBV_ADD, { node[0][1], node[1] }), node[0][1] }), nm->mkNode(Kind::PBV_LSHR, { node[0][0], nm->mkNode(Kind::PBV_ADD, { node[0][1], node[1] }) }), nm->mkNode(Kind::INT_TO_PBV, { nm->mkNode(Kind::PBV_SIZE, { node[0][0] }), nm->mkConstInt(Rational(0)) }) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_merge_lshr);
    }

  }  // Kind::PBV_LSHR

  // --- Kind::PBV_MULT ---
  if (node.getKind() == Kind::PBV_MULT)
  {
    // Rule: pbv-mul-one
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(1)))
    {
      Node rhs_pbv_mul_one = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_mul_one);
    }

    // Rule: pbv-mul-zero
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_mul_zero = nm->mkNode(Kind::INT_TO_PBV, { node[1][0], nm->mkConstInt(Rational(0)) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_mul_zero);
    }

    // Rule: pbv-mul-two
    if (
d_rwMerge        && (node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(2)))
    {
      Node rhs_pbv_mul_two = nm->mkNode(Kind::PBV_ADD, { node[0], node[0] });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_mul_two);
    }

  }  // Kind::PBV_MULT

  // --- Kind::PBV_NEG ---
  if (node.getKind() == Kind::PBV_NEG)
  {
    // Rule: pbv-neg-sub
    if (
(node[0].getKind() == Kind::PBV_SUB))
    {
      Node rhs_pbv_neg_sub = nm->mkNode(Kind::PBV_SUB, { node[0][1], node[0][0] });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_neg_sub);
    }

    // Rule: pbv-neg-idemp
    if (
(node[0].getKind() == Kind::PBV_NEG))
    {
      Node rhs_pbv_neg_idemp = node[0][0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_neg_idemp);
    }

  }  // Kind::PBV_NEG

  // --- Kind::PBV_NOT ---
  if (node.getKind() == Kind::PBV_NOT)
  {
    // Rule: pbv-not-idemp
    if (
(node[0].getKind() == Kind::PBV_NOT))
    {
      Node rhs_pbv_not_idemp = node[0][0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_not_idemp);
    }

  }  // Kind::PBV_NOT

  // --- Kind::PBV_OR ---
  if (node.getKind() == Kind::PBV_OR)
  {
    // Rule: pbv-or-zero
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_or_zero = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_or_zero);
    }

    // Rule: pbv-or-one
    if (
(node[1].getKind() == Kind::PBV_NOT)        && (node[1][0].getKind() == Kind::INT_TO_PBV)        && (node[1][0][1].isConst() && node[1][0][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_or_one = nm->mkNode(Kind::PBV_NOT, { nm->mkNode(Kind::INT_TO_PBV, { node[1][0][0], nm->mkConstInt(Rational(0)) }) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_or_one);
    }

    // Rule: pbv-bitwise-idemp-2
    if (
(node[0] == node[1]))
    {
      Node rhs_pbv_bitwise_idemp_2 = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_bitwise_idemp_2);
    }

  }  // Kind::PBV_OR

  // --- Kind::PBV_SGE ---
  if (node.getKind() == Kind::PBV_SGE)
  {
    // Rule: pbv-sge-eliminate
    Node rhs_pbv_sge_eliminate = nm->mkNode(Kind::PBV_SLE, { node[1], node[0] });
    return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_sge_eliminate);

  }  // Kind::PBV_SGE

  // --- Kind::PBV_SGT ---
  if (node.getKind() == Kind::PBV_SGT)
  {
    // Rule: pbv-sgt-eliminate
    Node rhs_pbv_sgt_eliminate = nm->mkNode(Kind::PBV_SLT, { node[1], node[0] });
    return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_sgt_eliminate);

  }  // Kind::PBV_SGT

  // --- Kind::PBV_SHL ---
  if (node.getKind() == Kind::PBV_SHL)
  {
    // Rule: pbv-shl-by-const-0
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_shl_by_const_0 = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_shl_by_const_0);
    }

    // Rule: pbv-shl-by-const-2
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][0] == node[1][1]))
    {
      Node rhs_pbv_shl_by_const_2 = nm->mkNode(Kind::INT_TO_PBV, { node[1][0], nm->mkConstInt(Rational(0)) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_shl_by_const_2);
    }

    // Rule: pbv-shl-zero
    if (
(node[0].getKind() == Kind::INT_TO_PBV)        && (node[0][1].isConst() && node[0][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_shl_zero = nm->mkNode(Kind::INT_TO_PBV, { node[0][0], nm->mkConstInt(Rational(0)) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_shl_zero);
    }

    // Rule: pbv-merge-shl
    if (
d_rwMerge        && (node[0].getKind() == Kind::PBV_SHL))
    {
      Node rhs_pbv_merge_shl = nm->mkNode(Kind::ITE, { nm->mkNode(Kind::PBV_UGE, { nm->mkNode(Kind::PBV_ADD, { node[0][1], node[1] }), node[0][1] }), nm->mkNode(Kind::PBV_SHL, { node[0][0], nm->mkNode(Kind::PBV_ADD, { node[0][1], node[1] }) }), nm->mkNode(Kind::INT_TO_PBV, { nm->mkNode(Kind::PBV_SIZE, { node[0][0] }), nm->mkConstInt(Rational(0)) }) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_merge_shl);
    }

  }  // Kind::PBV_SHL

  // --- Kind::PBV_SIGN_EXTEND ---
  if (node.getKind() == Kind::PBV_SIGN_EXTEND)
  {
    // Rule: pbv-sign-extend-eliminate
    if (
(node[0].isConst() && node[0].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_sign_extend_eliminate = node[1];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_sign_extend_eliminate);
    }

    // Rule: pbv-merge-sext
    if (
d_rwMerge        && (node[1].getKind() == Kind::PBV_SIGN_EXTEND))
    {
      Node rhs_pbv_merge_sext = nm->mkNode(Kind::PBV_SIGN_EXTEND, { nm->mkNode(Kind::ADD, { node[0], node[1][0] }), node[1][1] });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_merge_sext);
    }

  }  // Kind::PBV_SIGN_EXTEND

  // --- Kind::PBV_SLE ---
  if (node.getKind() == Kind::PBV_SLE)
  {
    // Rule: pbv-sle-self
    if (
(node[0] == node[1]))
    {
      Node rhs_pbv_sle_self = nm->mkConst(true);
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_sle_self);
    }

  }  // Kind::PBV_SLE

  // --- Kind::PBV_SLT ---
  if (node.getKind() == Kind::PBV_SLT)
  {
    // Rule: pbv-slt-self
    if (
(node[0] == node[1]))
    {
      Node rhs_pbv_slt_self = nm->mkConst(false);
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_slt_self);
    }

  }  // Kind::PBV_SLT

  // --- Kind::PBV_SUB ---
  if (node.getKind() == Kind::PBV_SUB)
  {
    // Rule: pbv-sub-zero
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_sub_zero = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_sub_zero);
    }

  }  // Kind::PBV_SUB

  // --- Kind::PBV_UDIV ---
  if (node.getKind() == Kind::PBV_UDIV)
  {
    // Rule: pbv-udiv-zero
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_udiv_zero = nm->mkNode(Kind::PBV_NOT, { nm->mkNode(Kind::INT_TO_PBV, { node[1][0], nm->mkConstInt(Rational(0)) }) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_udiv_zero);
    }

    // Rule: pbv-udiv-one
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(1)))
    {
      Node rhs_pbv_udiv_one = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_udiv_one);
    }

  }  // Kind::PBV_UDIV

  // --- Kind::PBV_UGE ---
  if (node.getKind() == Kind::PBV_UGE)
  {
    // Rule: pbv-uge-eliminate
    Node rhs_pbv_uge_eliminate = nm->mkNode(Kind::PBV_ULE, { node[1], node[0] });
    return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_uge_eliminate);

  }  // Kind::PBV_UGE

  // --- Kind::PBV_UGT ---
  if (node.getKind() == Kind::PBV_UGT)
  {
    // Rule: pbv-ugt-eliminate
    Node rhs_pbv_ugt_eliminate = nm->mkNode(Kind::PBV_ULT, { node[1], node[0] });
    return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_ugt_eliminate);

  }  // Kind::PBV_UGT

  // --- Kind::PBV_ULE ---
  if (node.getKind() == Kind::PBV_ULE)
  {
    // Rule: pbv-ule-zero
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_ule_zero = nm->mkNode(Kind::EQUAL, { node[0], nm->mkNode(Kind::INT_TO_PBV, { node[1][0], nm->mkConstInt(Rational(0)) }) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_ule_zero);
    }

    // Rule: pbv-zero-ule
    if (
(node[0].getKind() == Kind::INT_TO_PBV)        && (node[0][1].isConst() && node[0][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_zero_ule = nm->mkConst(true);
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_zero_ule);
    }

    // Rule: pbv-ule-self
    if (
(node[0] == node[1]))
    {
      Node rhs_pbv_ule_self = nm->mkConst(true);
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_ule_self);
    }

    // Rule: pbv-ule-max
    if (
(node[1].getKind() == Kind::PBV_NOT)        && (node[1][0].getKind() == Kind::INT_TO_PBV)        && (node[1][0][1].isConst() && node[1][0][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_ule_max = nm->mkConst(true);
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_ule_max);
    }

  }  // Kind::PBV_ULE

  // --- Kind::PBV_ULT ---
  if (node.getKind() == Kind::PBV_ULT)
  {
    // Rule: pbv-ult-zero-1
    if (
(node[0].getKind() == Kind::INT_TO_PBV)        && (node[0][1].isConst() && node[0][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_ult_zero_1 = nm->mkNode(Kind::NOT, { nm->mkNode(Kind::EQUAL, { node[1], nm->mkNode(Kind::INT_TO_PBV, { node[0][0], nm->mkConstInt(Rational(0)) }) }) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_ult_zero_1);
    }

    // Rule: pbv-ult-zero-2
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_ult_zero_2 = nm->mkConst(false);
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_ult_zero_2);
    }

    // Rule: pbv-ult-one
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(1)))
    {
      Node rhs_pbv_ult_one = nm->mkNode(Kind::EQUAL, { node[0], nm->mkNode(Kind::INT_TO_PBV, { node[1][0], nm->mkConstInt(Rational(0)) }) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_ult_one);
    }

    // Rule: pbv-lt-self
    if (
(node[0] == node[1]))
    {
      Node rhs_pbv_lt_self = nm->mkConst(false);
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_lt_self);
    }

  }  // Kind::PBV_ULT

  // --- Kind::PBV_UREM ---
  if (node.getKind() == Kind::PBV_UREM)
  {
    // Rule: pbv-urem-one
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(1)))
    {
      Node rhs_pbv_urem_one = nm->mkNode(Kind::INT_TO_PBV, { node[1][0], nm->mkConstInt(Rational(0)) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_urem_one);
    }

    // Rule: pbv-urem-self
    if (
(node[0] == node[1]))
    {
      Node rhs_pbv_urem_self = nm->mkNode(Kind::INT_TO_PBV, { nm->mkNode(Kind::PBV_SIZE, { node[0] }), nm->mkConstInt(Rational(0)) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_urem_self);
    }

  }  // Kind::PBV_UREM

  // --- Kind::PBV_XOR ---
  if (node.getKind() == Kind::PBV_XOR)
  {
    // Rule: pbv-xor-zero
    if (
(node[1].getKind() == Kind::INT_TO_PBV)        && (node[1][1].isConst() && node[1][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_xor_zero = node[0];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_xor_zero);
    }

    // Rule: pbv-xor-duplicate
    if (
(node[0] == node[1]))
    {
      Node rhs_pbv_xor_duplicate = nm->mkNode(Kind::INT_TO_PBV, { nm->mkNode(Kind::PBV_SIZE, { node[0] }), nm->mkConstInt(Rational(0)) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_xor_duplicate);
    }

    // Rule: pbv-xor-not
    if (
(node[0].getKind() == Kind::PBV_NOT))
    {
      Node rhs_pbv_xor_not = nm->mkNode(Kind::PBV_NOT, { nm->mkNode(Kind::PBV_XOR, { node[0][0], node[1] }) });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_xor_not);
    }

    // Rule: pbv-c26-xor-allones
    if (
d_rwCav26        && (node[1].getKind() == Kind::PBV_NOT)        && (node[1][0].getKind() == Kind::INT_TO_PBV)        && (node[1][0][1].isConst() && node[1][0][1].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_c26_xor_allones = nm->mkNode(Kind::PBV_NOT, { node[0] });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_c26_xor_allones);
    }

  }  // Kind::PBV_XOR

  // --- Kind::PBV_ZERO_EXTEND ---
  if (node.getKind() == Kind::PBV_ZERO_EXTEND)
  {
    // Rule: pbv-zero-extend-eliminate
    if (
(node[0].isConst() && node[0].getConst<Rational>() == Rational(0)))
    {
      Node rhs_pbv_zero_extend_eliminate = node[1];
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_zero_extend_eliminate);
    }

    // Rule: pbv-merge-zext
    if (
d_rwMerge        && (node[1].getKind() == Kind::PBV_ZERO_EXTEND))
    {
      Node rhs_pbv_merge_zext = nm->mkNode(Kind::PBV_ZERO_EXTEND, { nm->mkNode(Kind::ADD, { node[0], node[1][0] }), node[1][1] });
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_merge_zext);
    }

  }  // Kind::PBV_ZERO_EXTEND

  // ---------------------------------------------------------------------------
  // Shift merge across a zero extension (--pbv-rw-shift-zext-merge, off by default)
  //
  //   (pbvlshr (pzero_extend n (pbvlshr x y)) z)
  //       -> ite( (pbvadd y' z) >=u z ,  (pbvlshr x' (pbvadd y' z)) ,  0 )
  //   where x' = (pzero_extend n x), y' = (pzero_extend n y); dually for pbvshl.
  //
  // pbv-merge-lshr requires the two shifts to be ADJACENT, so it never matches a
  // multi-width goal: there the intermediate width sits between them as exactly
  // this zero extension. And the integer-level nested-division merge cannot help
  // either, because the int-blaster purifies the divisions into skolems while
  // translating, before the mod-reduction pass runs.
  //
  // Zero extension preserves the value, so the composition is x div 2^(y+z) --
  // the same identity pbv-merge-lshr proves for adjacent shifts, with the same
  // overflow guard, since y'+z is computed mod 2^|z| and can wrap.
  // ---------------------------------------------------------------------------
  if (d_rwShiftZext
      && (node.getKind() == Kind::PBV_LSHR || node.getKind() == Kind::PBV_SHL)
      && node.getNumChildren() == 2
      && node[0].getKind() == Kind::PBV_ZERO_EXTEND
      && node[0].getNumChildren() == 2
      && node[0][1].getKind() == node.getKind()
      && node[0][1].getNumChildren() == 2)
  {
    Kind sk = node.getKind();
    Node n0 = node[0][0];          // the extension amount
    Node x = node[0][1][0];
    Node y = node[0][1][1];
    Node z = node[1];
    Node xe = nm->mkNode(Kind::PBV_ZERO_EXTEND, {n0, x});
    Node ye = nm->mkNode(Kind::PBV_ZERO_EXTEND, {n0, y});
    Node sum = nm->mkNode(Kind::PBV_ADD, {ye, z});
    Node noOverflow = nm->mkNode(Kind::PBV_UGE, {sum, z});
    Node zero = nm->mkNode(Kind::INT_TO_PBV,
                           {nm->mkNode(Kind::PBV_SIZE, {z}),
                            nm->mkConstInt(Rational(0))});
    Node merged = nm->mkNode(sk, {xe, sum});
    return RewriteResponse(REWRITE_AGAIN_FULL,
                           nm->mkNode(Kind::ITE, {noOverflow, merged, zero}));
  }

  // ---------------------------------------------------------------------------
  // Boolean decision for bitwise equalities (--pbv-rw-bool, off by default)
  //
  // pbvand/pbvor/pbvxor/pbvnot act on each bit independently and identically,
  // so two such terms denote the same value at EVERY width exactly when the
  // Boolean functions they define over their leaves coincide. Enumerating the
  // leaf assignments therefore DECIDES this fragment -- which is what parabit
  // reaches only by saturating an e-graph with bidirectional xor_as_or_and and
  // and_distrib. A destructive rewriter cannot saturate, so it decides instead.
  //
  // A non-bitwise leaf is treated as an independent variable. That is sound for
  // concluding equality (agreement for every value of the leaf implies
  // agreement for its actual value) and merely costs completeness. Note the
  // converse is NOT available: differing tables cannot refute the goal, because
  // the leaves need not be independent, so this only ever returns true.
  // ---------------------------------------------------------------------------
  if (d_rwBool && node.getKind() == Kind::EQUAL && node.getNumChildren() == 2
      && node[0].getType().isPbv() && node[0] != node[1]
      && (isBitwise(node[0]) || isBitwise(node[1])))
  {
    std::vector<Node> leaves;
    if (boolLeaves(node[0], leaves, d_boolCap)
        && boolLeaves(node[1], leaves, d_boolCap) && !leaves.empty()
        && leaves.size() <= d_boolCap)
    {
      bool same = true;
      uint64_t rows = uint64_t(1) << leaves.size();
      for (uint64_t a = 0; a < rows; ++a)
      {
        if (boolEval(node[0], leaves, a) != boolEval(node[1], leaves, a))
        {
          same = false;
          break;
        }
      }
      if (same)
      {
        return RewriteResponse(REWRITE_DONE, nm->mkConst(true));
      }
    }
  }

  // ---------------------------------------------------------------------------
  // De Morgan / negation normal form (--pbv-rw-nnf, off by default)
  //
  //   (pbvnot (pbvand x y))  ->  (pbvor  (pbvnot x) (pbvnot y))
  //   (pbvnot (pbvor  x y))  ->  (pbvand (pbvnot x) (pbvnot y))
  //
  // Terminating: each application moves a negation one level toward the leaves,
  // and pbv-not-idemp collapses the doubled ones, so the fixpoint is NNF.
  //
  // The term gets bigger, which is the whole point of it being opt-in -- what it
  // buys is a canonical DIRECTION. Goals in this family are written as
  // `(and (xor a ~0) (xor b ~0)) = (xor (or a b) ~0)`; --pbv-rw-mw=cav26 turns
  // `xor all-ones` into pbvnot, and then one side is `(and (not a) (not b))` and
  // the other `(not (or a b))`. Without De Morgan those are distinct terms and
  // the equality goes to the arithmetic solver as a piand query; with it, both
  // normalize to the same term and the goal closes in the rewriter.
  // ---------------------------------------------------------------------------
  if (d_rwNnf && node.getKind() == Kind::PBV_NOT && node.getNumChildren() == 1
      && (node[0].getKind() == Kind::PBV_AND
          || node[0].getKind() == Kind::PBV_OR)
      && node[0].getNumChildren() == 2)
  {
    Kind inner = node[0].getKind();
    Kind flipped = (inner == Kind::PBV_AND) ? Kind::PBV_OR : Kind::PBV_AND;
    Node nx = nm->mkNode(Kind::PBV_NOT, {node[0][0]});
    Node ny = nm->mkNode(Kind::PBV_NOT, {node[0][1]});
    return RewriteResponse(REWRITE_AGAIN_FULL,
                           nm->mkNode(flipped, {nx, ny}));
  }

  // ---------------------------------------------------------------------------
  // AC normalization for the associative-commutative operators
  // (--pbv-rw-ac, off by default): pbvand/pbvor/pbvxor and pbvadd/pbvmul.
  //
  // pbvand/pbvor/pbvxor are associative and commutative, but nothing in RW_B
  // canonicalizes the SHAPE of a nested chain. So `(x & y) & z` and
  // `x & (y & z)` stay distinct terms, and an equality between them survives
  // preprocessing and is handed to the arithmetic solver as a piand query --
  // which blows up once the leaves are symbolic-width extracts. parabit closes
  // exactly these by saturating with and.assoc / and.commute.
  //
  // Here: flatten the same-kind chain to its leaves, order them canonically,
  // drop duplicates for and/or (idempotent), and rebuild. pbvxor is ordered but
  // NOT deduplicated -- x xor x is 0, not x, and the binary case already has
  // its own rule.
  //
  // The chain is rebuilt RIGHT-ASSOCIATED and BINARY: PbvTypeRule asserts a
  // bitwise node has exactly two children, so an n-ary node must not be built.
  //
  // Width note: the encoding takes kappa(parent) = kappa(child 0), so moving a
  // different leaf into position 0 is only sound because the admissibility
  // constraints equate the operand widths, and the translation always asserts
  // them.
  if (d_rwAc
      && (node.getKind() == Kind::PBV_AND || node.getKind() == Kind::PBV_OR
          || node.getKind() == Kind::PBV_XOR || node.getKind() == Kind::PBV_ADD
          || node.getKind() == Kind::PBV_MULT))
  {
    Kind bk = node.getKind();
    // Flatten the same-kind chain into its leaves.
    std::vector<Node> leaves;
    std::vector<TNode> work{node};
    while (!work.empty())
    {
      TNode cur = work.back();
      work.pop_back();
      if (cur.getKind() == bk)
      {
        for (size_t ci = cur.getNumChildren(); ci-- > 0;)
        {
          work.push_back(cur[ci]);
        }
      }
      else
      {
        leaves.emplace_back(cur);
      }
    }
    if (leaves.size() >= 2)
    {
      std::vector<Node> norm = leaves;
      std::sort(norm.begin(), norm.end());
      // Idempotence holds for and/or only: x xor x is 0, x + x is 2x, and
      // x * x is x^2, so duplicates must survive everywhere else.
      if (bk == Kind::PBV_AND || bk == Kind::PBV_OR)
      {
        norm.erase(std::unique(norm.begin(), norm.end()), norm.end());
      }
      Node rebuilt;
      if (norm.size() == 1)
      {
        // Only reachable for and/or, where dedup collapsed every leaf to one.
        rebuilt = norm[0];
      }
      else
      {
        rebuilt = norm.back();
        for (size_t li = norm.size() - 1; li-- > 0;)
        {
          rebuilt = nm->mkNode(bk, {norm[li], rebuilt});
        }
      }
      if (rebuilt != node)
      {
        return RewriteResponse(REWRITE_AGAIN_FULL, rebuilt);
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Raw C++ rules (width-dependent RHS; not expressible in RARE DSL)
  // Source: Appendix A, "Bit-Precise Reasoning with Parametric Bit-Vectors"
  //         Berger, Zohar, Niemetz, Preiner, Reynolds, Barrett, Tinelli (SAT 2025)
  // ---------------------------------------------------------------------------

  // pbv-add-self: (pbvadd x (pbvneg x)) => (int_to_pbv (pbvsize x) 0)
  if (node.getKind() == Kind::PBV_ADD && node.getNumChildren() == 2)
  {
    if (node[1].getKind() == Kind::PBV_NEG && node[0] == node[1][0])
    {
      Node width_add_self = nm->mkNode(Kind::PBV_SIZE, {node[0]});
      Node rhs_pbv_add_self =
          nm->mkNode(Kind::INT_TO_PBV, {width_add_self, nm->mkConstInt(Rational(0))});
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_add_self);
    }
  }

  // pbv-bitwise-not-or: (pbvor x (pbvnot x)) => (pbvnot (int_to_pbv (pbvsize x) 0))
  if (node.getKind() == Kind::PBV_OR && node.getNumChildren() == 2)
  {
    if (node[1].getKind() == Kind::PBV_NOT && node[0] == node[1][0])
    {
      Node width_not_or = nm->mkNode(Kind::PBV_SIZE, {node[0]});
      Node zero_not_or =
          nm->mkNode(Kind::INT_TO_PBV, {width_not_or, nm->mkConstInt(Rational(0))});
      Node rhs_pbv_bitwise_not_or = nm->mkNode(Kind::PBV_NOT, {zero_not_or});
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_bitwise_not_or);
    }
  }

  // pbv-xor-duplicate:   (pbvxor x x)          => (int_to_pbv (pbvsize x) 0)
  // pbv-xor-simplify-2:  (pbvxor x (pbvnot x)) => (pbvnot (int_to_pbv (pbvsize x) 0))
  if (node.getKind() == Kind::PBV_XOR && node.getNumChildren() == 2)
  {
    if (node[0] == node[1])
    {
      Node width_xor_dup = nm->mkNode(Kind::PBV_SIZE, {node[0]});
      Node rhs_pbv_xor_duplicate =
          nm->mkNode(Kind::INT_TO_PBV, {width_xor_dup, nm->mkConstInt(Rational(0))});
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_xor_duplicate);
    }
    if (node[1].getKind() == Kind::PBV_NOT && node[0] == node[1][0])
    {
      Node width_xor_s2 = nm->mkNode(Kind::PBV_SIZE, {node[0]});
      Node zero_xor_s2 =
          nm->mkNode(Kind::INT_TO_PBV, {width_xor_s2, nm->mkConstInt(Rational(0))});
      Node rhs_pbv_xor_simplify_2 = nm->mkNode(Kind::PBV_NOT, {zero_xor_s2});
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_xor_simplify_2);
    }
  }

  // pbv-urem-self: (pbvurem x x) => (int_to_pbv (pbvsize x) 0)
  if (node.getKind() == Kind::PBV_UREM)
  {
    if (node[0] == node[1])
    {
      Node width_urem_self = nm->mkNode(Kind::PBV_SIZE, {node[0]});
      Node rhs_pbv_urem_self =
          nm->mkNode(Kind::INT_TO_PBV, {width_urem_self, nm->mkConstInt(Rational(0))});
      return RewriteResponse(REWRITE_AGAIN_FULL, rhs_pbv_urem_self);
    }
  }


  return RewriteResponse(REWRITE_DONE, node);
}

}  // namespace pbv
}  // namespace theory
}  // namespace cvc5::internal
